---

- name: Converge
  hosts: all
  become: true
  become_user: root
  roles:
    - role: common
    - role: checkmk
  vars:
    checkmk_url: checkmk.valhallaonline.info
    checkmk_instance_name: cmk
    checkmk_firewall: true
    ssh_port: 22
    checkmk_agent_port: 6556
    check_mk_server_ip: 123.123.123.123
