---

- name: Allowing ssh from checkmk
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    source: '{{ check_mk_server_ip }}'
    destination_port: '{{ ssh_port }}'
    jump: ACCEPT

- name: Allowing checkmk agent port
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    source: '{{ check_mk_server_ip }}'
    destination_port: '{{ checkmk_agent_port }}'
    jump: ACCEPT
