---

- name: Installing agent from RPM
  ansible.builtin.yum:
    name: 'https://{{ checkmk_url }}/{{ checkmk_instance_name }}/check_mk/agents/check-mk-agent-{{ checkmk_version }}-1.noarch.rpm'
    state: present
    disable_gpg_check: true
  when: ansible_os_family == 'RedHat'

- name: Installing agent from DEB
  ansible.builtin.apt:
    deb: 'https://{{ checkmk_url }}/{{ checkmk_instance_name }}/check_mk/agents/check-mk-agent_{{ checkmk_version }}-1_all.deb'
  when: ansible_os_family == 'Debian'
